# Generated by Django 2.0.4 on 2018-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateRecord',
            fields=[
                ('words_text', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_quest_date', models.DateTimeField(verbose_name='date published')),
                ('quest_num', models.IntegerField(default=1)),
                ('src_content', models.TextField()),
                ('display_content', models.TextField()),
                ('is_rembered', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
